apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "<SOLUTION_REPOSITORY>.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  CONFIG_ONE: your-first-config
  CONFIG_TWO: your-second-config
