apiVersion: v1
kind: Service
metadata:
  name: {{ include "<SOLUTION_REPOSITORY>.fullname" . }}
  labels:
    {{- include "<SOLUTION_REPOSITORY>.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "<SOLUTION_REPOSITORY>.selectorLabels" . | nindent 4 }}
