[global]
path = "gs"
scm = "github"
owner = "ssotops"

[auth]
type = "ssh"
key_path = "$SSH_KEY_PATH"

[groups.bots]
match = "isExactly"
values = ["bots"]

[groups.git]
match = "startsWith"
values = ["git"]

[groups.space]
match = "endsWith"
values = ["space", "plugin"]

[groups.sso]
match = "includes"
values = ["sso"]
